#liste numero : 7
a = {'feminin': 1, 'masculin': 0}
b = {'.': 10, ',': 5, ';': 2, '!': 2, '?': 0, ':': 0}
c = {'nb_phrase': 7, 'mot_phrase_max': 30}
d = [['pronom_personnel', 'verbe', 'verbe', 'Aucun_mot_trouvé', 'verbe', 'verbe', 'préposition', 'forme_article_défini', 'forme_article_défini', 'forme_de_nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'préposition', 'Forme_adjectif_numéral', 'nom_commun', 'préposition', 'Aucun_mot_trouvé', 'pronom_personnel', 'pronom_personnel', 'verbe', 'Aucun_mot_trouvé', 'pronom_personnel', 'pronom_personnel', 'verbe', 'Aucun_mot_trouvé', 'verbe', 'préposition', 'verbe', 'préposition', 'verbe', 'verbe', 'verbe', 'verbe', 'Aucun_mot_trouvé', 'conjonction_de_coordination', 'pronom_personnel', 'verbe', 'nom_commun', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'verbe', 'Aucun_mot_trouvé', 'conjonction_de_coordination', 'conjonction_de_coordination', 'préposition', 'verbe', 'adjectif', 'nom_commun', 'Aucun_mot_trouvé', 'verbe', 'verbe', 'conjonction_de_coordination', 'verbe', 'préposition', 'verbe', 'verbe', 'nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'pronom_personnel', 'verbe', 'adverbe', 'conjonction_de_coordination', 'verbe', 'verbe', 'verbe', 'Aucun_mot_trouvé', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'verbe', 'forme_article_défini', 'Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'forme_article_défini', 'verbe', 'adverbe', 'verbe', 'verbe', 'article_défini', 'nom_commun', 'préposition', 'article_défini', 'nom_commun', 'conjonction_de_coordination', 'pronom_personnel', 'verbe', 'verbe', 'pronom_personnel', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'préposition', 'verbe', 'conjonction', 'verbe', 'verbe', 'conjonction_de_coordination', 'conjonction', 'verbe', 'verbe', 'forme_article_défini', 'nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
e = []
f = (7, 2, 0, 1, 2, 3, 0, 0)
g = ['ma', 'tendre', 'ton', 'digne']
h = ['seule', 'quinzaine', 'bien', 'joie', 'mère', 'est', 'soir', 'balcon', 'plaisir', 'nature']
i = ['suis', 'seule', 'lisant', 'chères', 'reverrai', 'embrasserai', 'nous', 'aurons', 'longtemps', 'à', 'être', 'ensemble', 'serai', 'heureuse', 'Continue', 'faire', 'sois', 'attentive', 'tendre', 'ton', 'excellente', 'aime', 'est', 'si', 'digne', 'aimée', 'Toutes', 'regarde', 'étoiles', 'nous', 'faisions', 'pense', 'à', 'vois', 'plaisir', 'tu', 'aimes', 'tu', 'comprends']