#liste numero : 11
a = {'feminin': 1, 'masculin': 0}
b = {'.': 10, ',': 6, ';': 0, '!': 0, '?': 0, ':': 1}
c = {'nb_phrase': 6, 'mot_phrase_max': 47}
d = [['forme_article_dÃ©fini', 'verbe', 'Aucun_mot_trouvÃ©'], ['Aucun_mot_trouvÃ©', 'pronom_personnel', 'verbe', 'forme_article_dÃ©fini', 'verbe', 'conjonction_de_coordination', 'article_dÃ©fini', 'verbe', 'verbe', 'verbe', 'nom_commun', 'verbe', 'verbe', 'prÃ©position', 'Aucun_mot_trouvÃ©', 'verbe', 'Aucun_mot_trouvÃ©'], ['Aucun_mot_trouvÃ©', 'Forme_article_indÃ©fini', 'conjonction', 'verbe', 'verbe', 'prÃ©position', 'forme_article_dÃ©fini', 'verbe', 'Aucun_mot_trouvÃ©', 'Aucun_mot_trouvÃ©', 'verbe', 'adjectif', 'verbe', 'conjonction_de_coordination', 'verbe', 'verbe', 'Aucun_mot_trouvÃ©'], ['Aucun_mot_trouvÃ©', 'pronom_personnel', 'verbe', 'verbe', 'prÃ©position', 'verbe', 'article_dÃ©fini', 'nom_commun', 'Aucun_mot_trouvÃ©'], ['Aucun_mot_trouvÃ©', 'article_dÃ©fini', 'nom_commun', 'verbe', 'Aucun_mot_trouvÃ©', 'Aucun_mot_trouvÃ©', 'verbe', 'Aucun_mot_trouvÃ©', 'article_dÃ©fini', 'nom_commun', 'prÃ©position', 'verbe', 'prÃ©position', 'forme_article_dÃ©fini', 'nom_commun', 'verbe', 'verbe', 'Aucun_mot_trouvÃ©', 'Aucun_mot_trouvÃ©', 'prÃ©position', 'article_dÃ©fini', 'verbe', 'adjectif', 'Aucun_mot_trouvÃ©', 'adverbe', 'prÃ©position', 'adverbe', 'adjectif', 'Aucun_mot_trouvÃ©', 'Forme_article_indÃ©fini', 'verbe', 'Aucun_mot_trouvÃ©', 'Aucun_mot_trouvÃ©', 'Aucun_mot_trouvÃ©', 'Forme_article_indÃ©fini', 'Aucun_mot_trouvÃ©', 'verbe', 'forme_article_dÃ©fini', 'Aucun_mot_trouvÃ©'], ['Aucun_mot_trouvÃ©'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
e = []
f = (2, 0, 0, 0, 1, 0, 0, 0)
g = ['pris', 'un', 'grand', 'blanc', 'tranquille', 'sa', 'son', 'tournant', 'lointain', 'invisible']
h = ['barre', 'fantÃ´me', 'passe', 'marche', 'route', 'cap', 'jour', 'phare', 'fois', 'ciel']

i = ['embarquaient', 'pris', 'barre', 'à', 'un', 'grand', 'blanc', 'glissa', 'tranquille', 'nous', 'fûmes', 'passe', 'accéléra', 'marche', 'sembla', "s'animer", 'fis', 'route', 'doubler', 'naissait', "s'éteignaient", 'ferma', 'son', 'tournant', 'ciel', 'roses', 'allumait']
