#liste numero : 6
a = {'feminin': 1, 'masculin': 0}
b = {'.': 10, ',': 6, ';': 0, '!': 0, '?': 0, ':': 0}
c = {'nb_phrase': 6, 'mot_phrase_max': 43}
d = [['pronom_personnel', 'verbe', 'verbe', 'article_défini', 'nom_commun', 'préposition', 'verbe', 'verbe', 'verbe', 'article_défini', 'nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'article_défini', 'nom_commun', 'préposition', 'verbe', 'verbe', 'verbe', 'nom_commun', 'Aucun_mot_trouvé', 'verbe', 'préposition', 'verbe', 'Aucun_mot_trouvé', 'verbe', 'pronom_personnel', 'verbe', 'forme_article_défini', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'nom_commun', 'verbe', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'verbe', 'article_défini', 'nom_commun', 'verbe', 'nom_commun', 'conjonction_de_coordination', 'Aucun_mot_trouvé', 'verbe', 'nom_commun', 'conjonction', 'pronom_personnel', 'verbe', 'préposition', 'pronom_personnel', 'Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'verbe', 'préposition', 'verbe', 'adjectif', 'verbe', 'verbe', 'nom_commun', 'préposition', 'nom_commun', 'Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'verbe', 'préposition', 'pronom_personnel', 'conjonction_de_coordination', 'Aucun_mot_trouvé', 'adjectif', 'verbe', 'préposition', 'Aucun_mot_trouvé', 'préposition', 'adjectif', 'nom_commun', 'Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'Forme_article_indéfini', 'adjectif', 'verbe', 'verbe', 'préposition', 'adjectif', 'forme_de_nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
e = []
f = (4, 0, 0, 5, 0, 0, 0, 0)
g = ['assis', 'tombant', 'propice', 'un', 'sa', 'ses', 'deux', 'ses']
h = ['mur', 'borde', 'pré', 'soleil', 'juillet', 'pic', 'sorte', 'torpeur', 'vis', 'vipère', 'pas', 'pied', 'mur', 'obstacle', 'doute', 'bain', 'soleil', 'tête', 'anneaux']
i = ['assis', 'contre', 'pierres', 'sèches', 'borde', 'juillet', 'tombant', 'à', 'sorte', 'torpeur', 'lorsque', 'vis', 'vipère', 'ne', 'entendue', 'arriver', 'avait', 'dû', 'longer', 'du', 'rencontrant', 'représentais', "s'était", 'arrêtée', 'Trouvant', 'doute', 'à', 'un', "s'était", 'à', 'quelques', 'tête', 'me', 'regardait', 'perles', 'noires']