#liste numero : 13
a = {'feminin': 1, 'masculin': 0}
b = {'.': 8, ',': 5, ';': 0, '!': 2, '?': 0, ':': 0}
c = {'nb_phrase': 6, 'mot_phrase_max': 35}
d = [['nom_commun', 'verbe', 'conjonction_de_coordination', 'Forme_article_indéfini', 'adjectif', 'préposition', 'nom_commun', 'nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'forme_article_défini', 'Aucun_mot_trouvé', 'verbe', 'préposition', 'forme_article_défini', 'verbe', 'Aucun_mot_trouvé', 'verbe', 'adjectif', 'nom_commun', 'Aucun_mot_trouvé', 'verbe', 'adverbe', 'préposition', 'verbe', 'nom_commun', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'verbe', 'verbe', 'adverbe', 'adjectif', 'Forme_adjectif_numéral', 'verbe', 'verbe', 'verbe', 'préposition', 'Forme_adjectif_numéral', 'verbe', 'adverbe', 'verbe', 'Aucun_mot_trouvé', 'préposition', 'Aucun_mot_trouvé', 'adjectif', 'Aucun_mot_trouvé', 'préposition', 'adjectif', 'verbe', 'verbe', 'forme_article_défini', 'nom_commun', 'Aucun_mot_trouvé', 'adverbe', 'verbe', 'nom_commun', 'préposition', 'Forme_article_indéfini', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'Aucun_mot_trouvé', 'nom_commun', 'verbe', 'Aucun_mot_trouvé', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'forme_article_défini', 'verbe', 'Forme_article_indéfini', 'verbe', 'Aucun_mot_trouvé', 'conjonction_de_coordination', 'forme_article_défini', 'Aucun_mot_trouvé', 'verbe', 'adjectif', 'verbe', 'préposition', 'nom_commun', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
e = []
f = (2, 0, 0, 0, 0, 0, 0, 0)
g = ['deux', 'un', 'mince', 'son', 'haut', 'incroyable', 'plusieurs', 'un', 'deux', 'brillante']
h = ['Isabelle', 'même', 'temps', 'bracelet', 'poignet', 'main', 'fois', 'épervier', 'pas', 'statue', 'crispation', 'soie']
i = ['jouait', 'couraient', 'touches', 'un', 'dansait', 'son', 'Parfois,elle', 'levait', 'main', 'restait', 'suspendue', 'seconde', 'retombait', 'notes', 'à', 'un', 'plus', 'statue', 'regardais', 'crispation', 'épaules', 'entre', 'tresses', 'brillante']