#liste numero : 8
a = {'feminin': 1, 'masculin': 0}
b = {'.': 12, ',': 3, ';': 0, '!': 0, '?': 0, ':': 0}
c = {'nb_phrase': 7, 'mot_phrase_max': 25}
d = [['Aucun_mot_trouvé', 'verbe', 'adjectif', 'nom_commun', 'conjonction_de_coordination', 'pronom_personnel', 'adverbe', 'verbe', 'verbe', 'adjectif', 'préposition', 'verbe', 'conjonction', 'Aucun_mot_trouvé', 'conjonction', 'Aucun_mot_trouvé', 'verbe', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'Aucun_mot_trouvé', 'verbe', 'adjectif', 'Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'préposition', 'verbe', 'verbe', 'verbe', 'préposition', 'nom_commun', 'conjonction_de_coordination', 'pronom_personnel', 'verbe', 'verbe', 'article_défini', 'verbe', 'verbe', 'forme_article_défini', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'verbe', 'préposition', 'Aucun_mot_trouvé', 'article_défini', 'verbe', 'verbe', 'verbe', 'conjonction_de_coordination', 'Aucun_mot_trouvé', 'verbe', 'conjonction', 'verbe', 'verbe', 'verbe', 'verbe', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'verbe', 'verbe', 'verbe', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'conjonction_de_coordination', 'article_défini', 'verbe', 'Forme_article_indéfini', 'verbe', 'verbe', 'préposition', 'forme_article_défini', 'verbe', 'adverbe', 'Forme_adjectif_numéral', 'nom_commun', 'préposition', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'pronom_personnel', 'verbe', 'verbe', 'verbe', 'verbe', 'article_défini', 'verbe', 'Aucun_mot_trouvé'], ['Aucun_mot_trouvé', 'verbe', 'adjectif', 'Aucun_mot_trouvé', 'Forme_article_indéfini', 'verbe', 'verbe', 'verbe', 'préposition', 'article_défini', 'verbe'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
e = []
f = (4, 0, 1, 0, 1, 0, 0, 0)
g = ['ma', 'marchand', 'commode', 'deux', 'rentré', 'un', 'cru', 'un', 'découvert', 'cinq']
h = ['chaise', 'celle', 'tabac', 'fumée', 'morceau', 'chocolat', 'revenu', 'fenêtre', 'ciel', 'orage', 'passage', 'laissé', 'rue', 'promesse', 'ciel', 'bruit']
i = ['retournée', 'celle', 'du', 'tabac', 'plus', 'commode', 'fumée', 'suis', 'rentré', 'prendre', 'un', 'morceau', 'suis', 'revenu', 'manger', 'à', 'fenêtre', 'Peu', 'ciel', "s'est", 'assombri', 'cru', 'nous', 'allions', 'avoir', 'un', 'orage', "s'est", 'découvert', 'peu', 'à', 'peu', 'cependant', 'passage', 'avait', 'laissé', 'rue', 'suis', 'longtemps', 'à', 'regarder', 'ciel', 'À', 'tramways', 'sont', 'arrivés', 'bruit']
